# Build pf
# Pyer's Forth
# Pierre BAZONNARD
#40-Ubuntu SMP Wed May 23 20:30:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
#
require 'rake/clean'

task :default => [:x86]

task :help do
  puts "before compiling ARM architecture, set up environment: source /usr/local/angstrom/arm/environment-setup"
end

task :arm do
  ARCH='ARM'
# before compiling, set up environment:
# source /usr/local/angstrom/arm/environment-setup
  Rake::Task[:install].invoke
  sh "scp pf          bbb:/usr/bin/pf"
  sh "scp lib/pf.4th  bbb:/usr/etc/pf.4th"
end

task :x86 do
  ARCH='X86'
  Rake::Task[:install].invoke
  sh "sudo install -m 755 pf          /bin/pf"
  sh "sudo install -m 755 lib/pf.4th  /etc/pf.4th"
end

task :install => ['pf'] do
  puts "Architecture is #{ARCH}"
end

CLEAN.include('target')

directory 'target'

file 'pf' => ['target','target/main.o','target/compiler.o','target/core.o','target/exception.o','target/facility.o','target/interpret.o','target/file.o','target/floating.o','target/history.o','target/terminal.o','target/shell.o','target/signals.o','target/tools.o','target/version.o' ] do
  sh "gcc -D#{ARCH} -g -Wall -Wstrict-prototypes -fcommon -funsigned-char -fPIC -rdynamic -o pf target/main.o target/compiler.o target/core.o target/exception.o target/facility.o target/interpret.o target/file.o target/floating.o target/history.o target/terminal.o target/shell.o target/signals.o target/tools.o target/version.o -lm"
end

rule /target\/.*\.o/ => proc {|t| t.pathmap('src/%n.c')} do |t|
  object = t.source.ext('o').sub(/^src/,'target')
  sh "gcc -D#{ARCH} -Isrc -O1 -g -Wall -funsigned-char -fPIC -Wstrict-prototypes -c -o #{object} #{t.source}"
end

